title = "SDBLIBGO Application Configuration"

[database]
host="localhost"
port=65544
user="postgresql"
password="12345"
dbname="Student_Library_database_management_system"
sslmode=false

[server]
host="localhost"
port=5400