
CREATE TABLE LIB_MGMT.BOOK_BINDING_PUBLICATION (
	PUBLICATION_ID INTEGER DEFAULT NEXTVAL('LIB_MGMT.SEQ_BOOK_PUBLICATION_PUBLICATION_ID'),
	PUBLISHER_NAME VARCHAR(200) NOT NULL,
	PUBLICATION_YEAR VARCHAR(10) NOT NULL,
	PUBLISHED_DATE DATE,
	COPYRIGHT_YEAR VARCHAR(10),
	EDITION VARCHAR(10),
	BINDING_NAME VARCHAR(200),
	BINDING_TYPE VARCHAR(50),
	CONSTRAINT PUBLICATION_ID_PKEY PRIMARY KEY(PUBLICATION_ID)
);
