CREATE TABLE LIB_MGMT.BOOK_CATEGORY(
	CATEGORY_ID INTEGER,
	CATEGORY_NAME VARCHAR(100),
	STATUS CHARACTER VARYING(20),
    	CREATED_BY CHARACTER VARYING(50),
    	CREATED_TIME TIMESTAMP WITH TIME ZONE,
    	UPDATED_BY CHARACTER VARYING(50),
    	UPDATED_TIME TIMESTAMP WITH TIME ZONE,
	CONSTRAINT BOOK_CATEGORY_ID_PKEY PRIMARY KEY(CATEGORY_ID)
);