CREATE TABLE LIB_MGMT.BOOK_SHELVES(
	SHELF_ID INTEGER DEFAULT NEXTVAL('LIB_MGMT.SEQ_BOOK_SHELVES_SHELF_ID'),
	FLOOR_NO INTEGER,
	ROW_NO INTEGER,
	SHELF_NO INTEGER,
	STATUS CHARACTER VARYING(20),
    	CREATED_BY CHARACTER VARYING(50),
    	CREATED_TIME TIMESTAMP WITH TIME ZONE,
    	UPDATED_BY CHARACTER VARYING(50),
    	UPDATED_TIME TIMESTAMP WITH TIME ZONE,
	CONSTRAINT SHELF_ID_PKEY PRIMARY KEY(SHELF_ID),
	CONSTRAINT SHELF_NO_UK UNIQUE (SHELF_NO)
);