CREATE TABLE LIB_MGMT.BOOK_DETAILS (
	BOOK_ID INTEGER DEFAULT NEXTVAL('LIB_MGMT.SEQ_BOOK_DEATILS_BOOK_ID'),
	ISBN VARCHAR(20) NOT NULL,
	BOOK_TITLE VARCHAR(200) NOT NULL,
	LANGUAGE_NAME VARCHAR(50),
	TOTAL_NO_OF_COPIES INTEGER NOT NULL,
	CATEGORY_ID INTEGER NOT NULL,
	BINDING_PUBLICATION_ID INTEGER NOT NULL,
	SHELF_ID INTEGER NOT NULL,
	STATUS CHARACTER VARYING(20),
    CREATED_BY CHARACTER VARYING(50),
    CREATED_TIME TIMESTAMP WITH TIME ZONE,
    UPDATED_BY CHARACTER VARYING(50),
    UPDATED_TIME TIMESTAMP WITH TIME ZONE,
   	CONSTRAINT BOOK_ID_PKEY PRIMARY KEY(BOOK_ID),
	CONSTRAINT ISBN_CODE_UK UNIQUE(ISBN),
	CONSTRAINT BOOK_ID_FKEY FOREIGN KEY(CATEGORY_ID) 
		REFERENCES LIB_MGMT.BOOK_CATEGORY(CATEGORY_ID),
	CONSTRAINT BINDING_PUBLICATION_ID_FKEY FOREIGN KEY (BINDING_PUBLICATION_ID) 
		REFERENCES LIB_MGMT.BOOK_BINDING_PUBLICATION(PUBLICATION_ID),
	CONSTRAINT SHELF_ID_FKEY FOREIGN KEY(SHELF_ID) 
	REFERENCES LIB_MGMT.BOOK_SHELVES(SHELF_ID)
);
